markdown: kramdown
remote_theme: minima
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
title: The Deep Thinking Hour
description: A test page
author: "Samuele Papa"
