title: The Deep Thinking Hour
author:
  name: Samuele Papa
  email: saumuele.papa@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  The Deep Thinking Hour is an event at the University of Amsterdam, organized by the gorup lead by Efstratios Gavves. Researchers and students come together to
  discuss and learn about the state-of-the-art in Deep Learning. Generative models, dynamical systems, geometric deep learning are the main focus.
show_excerpts: true

# Minima date format
minima:
  date_format: "%b %-d, %Y"

include:
    - index.md
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
